[package]
name = "mset9-rs"
version = "2.0.0"
edition = "2024"

[dependencies]
console = "0.15.11"
dialoguer = "0.11.0"
fatfs = "0.3.6"
hex = "0.4.3"
sha2 = "0.10.9"
sysinfo = "0.35.1"
unicode-segmentation = "1.12.0"
