name: build

on:
  push:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-pc-windows-msvc
    - run: cargo build --release --target x86_64-pc-windows-msvc
    - uses: actions/upload-artifact@v4
      with:
        name: mset9-rs-win-64
        path: target/x86_64-pc-windows-msvc/release/mset9-rs.exe
